### ISSUE TITLE
dprint error with `"jsx.multiLineParens"` on `sane-fmt.typescript.json`

### ISSUE THREAD

**Issue by scarf005** [sane-fmt/sane-fmt#231]
### Environment

- Ubuntu 21.10 x86_64
- following guide from [dprint integration from official docs](https://github.com/sane-fmt/sane-fmt#use-with-dprint)
###  Error

```
❯ dprint fmt _config.ts
Error with 'https://github.com/sane-fmt/sane-fmt/blob/master/exports/sane-fmt.typescript.json'. Error deserializing. Unexpected token on line 7 column 1.
```

### How to solve

solution from error message seems to be:
```
Value is not accepted. Valid values: "never", "prefer", "always".(1)
```

**Comment by KSXGitHub** [comment]
It seems that I have to update dprint dependency yet again.

**Comment by scarf005** [comment]
thx for quick reply. other than that it works like charm, love semicolon-less deno experience.

**Comment by KSXGitHub** [comment]
The `sane-fmt.typescript.json` file has been updated in `master` branch. Can you try running dprint again before I push a new release?

**Comment by scarf005** [comment]
yes! 
however [link in preview from section](https://github.com/sane-fmt/sane-fmt#use-with-dprint) is not working on `dprint.json` does not work for some reason.
- `"https://github.com/sane-fmt/sane-fmt/raw/master/exports/sane-fmt.dprint.json"`
this does not work
![image](https://user-images.githubusercontent.com/54838975/147673411-0ea3ecdc-58cc-4550-90ec-38c0fee081a6.png)

however resolved link from this:
- `"https://raw.githubusercontent.com/sane-fmt/sane-fmt/master/exports/sane-fmt.dprint.json"` 
works.

![image](https://user-images.githubusercontent.com/54838975/147673435-9c8bbd61-56f5-426a-ad89-123c8d53c52c.png)

could you also take look at this? the vscode extension is [dprint code formatter](https://marketplace.visualstudio.com/items?itemName=dprint.dprint).

**Comment by KSXGitHub** [comment]
The error message suggests that the indirect link returns the old version of the config file. This appears to be a caching problem. This issue should solve itself sooner or later.

If you want to avoid this issue, you could:
1. Replace `master` in the link with a git ref (tag or commit). For example: `"https://github.com/sane-fmt/sane-fmt/raw/0.11.0/exports/sane-fmt.dprint.json"`.
2. Or just use the resolved link.
3. Or both. (i.e. replacing `master` in the resolved link with a git ref).
